sensors:
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon
    indices: [3, 6, 7]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0,  60]
  - [1, 60, 65]
  - [2, 65, 70]
  - [3, 70, 75]
  - [4, 75, 80]
  - [5, 80, 85]
  - [7, 65, 74]
  - [127, 70, 32767]
